### ISSUE TITLE
Case Diagram Comment

### ISSUE THREAD

**Issue by hujo22** [alexweininger/android-catan-layout#9]
It doesn't seem that "Lose Resources" should be on the diagram. Isn't it a side-effect of another action, rather than the player directly lose a resource?

**Comment by alexweininger** [comment]
Since rolling the robber (7) forces all players who have more than 7 cards, **including the player who rolled the robber**, must discard (or lose) half of their resource cards.

In that sense, it made sense to us to include "Lose Resources" on the diagram.

Thanks for your feedback.
